[tool.poetry]
<<<<<<< HEAD
name = "code-specialist-example-package"
version = "1.0.0"
description = "Test package"
authors = ["Yannic Schröer"]
packages = [{include = "example_package"}]
=======
name = "testing-github-action"
version = "1.0.2"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "testing_github_action"}]
>>>>>>> c5a5de06cdb4d5b773a39461813138e9ea21f9ce

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
