name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish PyPI package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_USER: ${{ secrets.PYPI_USER }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PUBLISH_REGISTRY: "https://pypi.tebuto.com"
          POETRY_DEPENDENCY_REGISTRY_URL: "https://pypi.tebuto.com"
          POETRY_DEPENDENCY_REGISTRY_NAME: "tebuto"
          POETRY_DEPENDENCY_REGISTRY_USERNAME: ${{ secrets.PYPI_USER }}
          POETRY_DEPENDENCY_REGISTRY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
